[alias]
wasm = "build --release --lib --target wasm32-unknown-unknown"
unit-test = "test --lib"
schema = "run --bin schema"
# integratdoion-test = "test --lib integration_tests"
clippy-all = "clippy --all-targets"